-- Drops everything and truncate exceptions
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE CONTACTINFO CASCADE CONSTRAINTS'; 
    EXECUTE IMMEDIATE 'DROP TABLE LOG CASCADE CONSTRAINTS'; 
    EXECUTE IMMEDIATE 'DROP TABLE MESSAGE CASCADE CONSTRAINTS'; 
    EXECUTE IMMEDIATE 'DROP TABLE KEYVALUES CASCADE CONSTRAINTS'; 
    EXECUTE IMMEDIATE 'DROP TABLE ATTACHMENT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP SEQUENCE CONTACTINFO_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE MESSAGE_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE KEYVALUES_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE LOG_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE ATTACHMENT_SEQ';
    EXCEPTION WHEN OTHERS THEN NULL; 
END;
/