/****** Object:  Table [dbo].[ATTACHMENT]    Script Date: 29.05.2012 13:24:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATTACHMENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MESSAGEID] [bigint] NOT NULL,
	[ATTACHMENT] [varchar](max) NOT NULL,
	[MIMETYPE] [varchar](255) NOT NULL,
	[FILENAME] [varchar](255) NOT NULL,
	[NAME] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONTACTINFO]    Script Date: 29.05.2012 13:24:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONTACTINFO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MESSAGEID] [bigint] NOT NULL,
	[TYPE] [varchar](10) NOT NULL,
	[ADDRESS] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[KEYVALUES]    Script Date: 29.05.2012 13:24:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KEYVALUES](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[KEY_NAME] [varchar](20) NULL,
	[DATEVALUE] [datetime] NULL,
	[NUMERICVALUE] [int] NULL,
	[STRINGVALUE] [varchar](4000) NULL,
	[DESCRIPTION] [varchar](4000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_KEYVALUES_KEYNAME] UNIQUE NONCLUSTERED 
(
	[KEY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOG]    Script Date: 29.05.2012 13:24:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MESSAGEID] [bigint] NULL,
	[TIME] [datetime] NULL,
	[logType] [varchar](1024) NOT NULL,
	[LOGMSG] [varchar](1024) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MESSAGE]    Script Date: 29.05.2012 13:24:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MESSAGE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MESSAGEKEY] [varchar](80) NOT NULL,
	[SENDINGSYSTEM] [varchar](15) NOT NULL,
	[BATCHSENDING] [int] NOT NULL,
	[DOMAIN] [varchar](10) NOT NULL,
	[CASEDESCRIPTION] [varchar](2000) NULL,
	[CASEOFFICER] [varchar](50) NULL,
	[PARTICIPANTID] [varchar](11) NOT NULL,
	[MESSAGEREFERENCE] [varchar](40) NOT NULL,
	[IDPROC] [varchar](40) NOT NULL,
	[DUEDATE] [datetime] NULL,
	[ALTINNARCHIVE] [varchar](50) NULL,
	[MESSAGEHEADER] [varchar](512) NOT NULL,
	[MESSAGESUMMARY] [varchar](2000) NOT NULL,
	[SENTALTINN] [int] NOT NULL,
	[SENTALTINNDATE] [datetime] NULL,
	[MSG_STATUS] [int] NOT NULL,
	[READDEADLINE] [datetime] NOT NULL,
	[OVERDUENOTICESENT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MESSAGEKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_MESSAGE_MESSAGEREFERENCE] UNIQUE NONCLUSTERED 
(
	[MESSAGEREFERENCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FKA7E14523E49456E] FOREIGN KEY([MESSAGEID])
REFERENCES [dbo].[MESSAGE] ([ID])
GO
ALTER TABLE [dbo].[ATTACHMENT] CHECK CONSTRAINT [FKA7E14523E49456E]
GO
ALTER TABLE [dbo].[CONTACTINFO]  WITH CHECK ADD  CONSTRAINT [FK82CD0CAEE49456E] FOREIGN KEY([MESSAGEID])
REFERENCES [dbo].[MESSAGE] ([ID])
GO
ALTER TABLE [dbo].[CONTACTINFO] CHECK CONSTRAINT [FK82CD0CAEE49456E]
GO
ALTER TABLE [dbo].[LOG]  WITH CHECK ADD  CONSTRAINT [FK12724E49456E] FOREIGN KEY([MESSAGEID])
REFERENCES [dbo].[MESSAGE] ([ID])
GO
ALTER TABLE [dbo].[LOG] CHECK CONSTRAINT [FK12724E49456E]
GO
ALTER TABLE [dbo].[CONTACTINFO]  WITH CHECK ADD CHECK  (([TYPE]='EMAIL' OR [TYPE]='SMS'))
GO
ALTER TABLE [dbo].[MESSAGE]  WITH CHECK ADD CHECK  (([BATCHSENDING]=(1) OR [BATCHSENDING]=(0)))
GO
ALTER TABLE [dbo].[MESSAGE]  WITH CHECK ADD CHECK  (([OVERDUENOTICESENT]=(1) OR [OVERDUENOTICESENT]=(0)))
GO
ALTER TABLE [dbo].[MESSAGE]  WITH CHECK ADD CHECK  (([SENTALTINN]=(1) OR [SENTALTINN]=(0)))
GO
